<select name="SSR_CLSRCH_WRK_SUBJECT_SRCH$0" id="SSR_CLSRCH_WRK_SUBJECT_SRCH$0" tabindex="52" size="1" class="PSDROPDOWNLIST" style="width:194px; ">
<option value="" selected="selected">&nbsp; </option>
<option value="ACCTCY">Accountancy</option>
<option value="AERO">Aerospace Studies</option>
<option value="AFNR">Ag, Food and Natural Resources</option>
<option value="AG_EC">Agricultural Economics</option>
<option value="AG_ED_LD">Agricultural Ed &amp; Leadership</option>
<option value="AG_S_M">Agricultural Systems Managemen</option>
<option value="ANESTH">Anesthesiology</option>
<option value="AN_SCI">Animal Science</option>
<option value="ANTHRO">Anthropology</option>
<option value="ARABIC">Arabic</option>
<option value="ARCHST">Architectural Studies</option>
<option value="AR_H_A">Art History And Archaeology</option>
<option value="ART_CERM">Art-Ceramics</option>
<option value="ART_DRAW">Art-Drawing</option>
<option value="ART_FIBR">Art-Fibers</option>
<option value="ART_GNRL">Art-General</option>
<option value="ART_GRDN">Art-Graphic Design</option>
<option value="ART_PNT">Art-Painting</option>
<option value="ART_PHOT">Art-Photography</option>
<option value="ART_PRNT">Art-Printmaking</option>
<option value="ART_SCUL">Art-Sculpture</option>
<option value="ASTRON">Astronomy</option>
<option value="ATHTRN">Athletic Training</option>
<option value="ATM_SC">Atmospheric Science</option>
<option value="BIOCHM">Biochemistry</option>
<option value="BIOL_EN">Biological Engineering</option>
<option value="BIO_SC">Biological Sciences</option>
<option value="BIOMED">Biomedical Sciences</option>
<option value="BL_STU">Black Studies</option>
<option value="BUS_AD">Business Administration</option>
<option value="CH_ENG">Chemical Engineering</option>
<option value="CHEM">Chemistry</option>
<option value="CH_HTH">Child Health</option>
<option value="CHINSE">Chinese</option>
<option value="CV_ENG">Civil Engineering</option>
<option value="CL_HUM">Classical Humanities</option>
<option value="CLASS">Classics</option>
<option value="CDS">Clinical &amp; Diagnostic Sciences</option>
<option value="CL_L_S">Clinical Laboratory Sciences</option>
<option value="COMMUN">Communication</option>
<option value="C_S_D">Communication Science/Disorder</option>
<option value="CMP_SC">Computer Science</option>
<option value="DERM">Dermatology</option>
<option value="DMU">Diagnostic Medical Ultrasound</option>
<option value="ECONOM">Economics</option>
<option value="ED_LPA">Ed Ldrshp and Policy Analysis</option>
<option value="ESC_PS">Ed, School and Counseling Psy</option>
<option value="EDUC_H">Education Honors</option>
<option value="ECE">Electrical And Computer Engine</option>
<option value="EMR_ME">Emergency Medicine</option>
<option value="ENGINR">Engineering</option>
<option value="ENGLSH">English</option>
<option value="ELSP">English Language Support Prgrm</option>
<option value="ENV_SC">Environmental Science</option>
<option value="ENV_ST">Environmental Studies</option>
<option value="F_C_MD">Family And Community Medicine</option>
<option value="FILM_S">Film Studies</option>
<option value="FINANC">Finance</option>
<option value="F_W">Fisheries And Wildlife</option>
<option value="F_S">Food Science</option>
<option value="FOREST">Forestry</option>
<option value="FRENCH">French</option>
<option value="G_STDY">General Studies</option>
<option value="GEOG">Geography</option>
<option value="GEOL">Geology</option>
<option value="GERMAN">German</option>
<option value="GRAD">Graduate School</option>
<option value="GREEK">Greek</option>
<option value="HMI">Health Management &amp; Informatic</option>
<option value="HTH_PR">Health Professions</option>
<option value="HLTH_SCI">Health Sciences</option>
<option value="HEBREW">Hebrew</option>
<option value="HIST">History</option>
<option value="GN_HON">Honors-General</option>
<option value="HSP_MGMT">Hospitality Management</option>
<option value="H_D_FS">Human Development And Family S</option>
<option value="IMSE">Industrial And Manufacturing S</option>
<option value="IS_LT">Info Science &amp; Learning Tech</option>
<option value="INFOTC">Information Technology</option>
<option value="NEUROSCI">Integrative Neuroscience</option>
<option value="INTDSC">Interdisciplinary Studies</option>
<option value="IN_MED">Internal Medicine</option>
<option value="INTL_S">International Studies</option>
<option value="ITAL">Italian</option>
<option value="JAPNSE">Japanese</option>
<option value="JOURN">Journalism</option>
<option value="KOREAN">Korean</option>
<option value="LAB_AN">Laboratory Animal Medicine</option>
<option value="LATIN">Latin</option>
<option value="LAW">Law</option>
<option value="LTC_V">Learning, Teach, &amp; Curr - Voc</option>
<option value="LTC">Learning, Teaching, &amp; Curric</option>
<option value="LINGST">Linguistics</option>
<option value="INFOINST">MU Informatics Institute</option>
<option value="MANGMT">Management</option>
<option value="MRKTNG">Marketing</option>
<option value="MATH">Mathematics</option>
<option value="MAE">Mechanical And Aerospace Engin</option>
<option value="MPP">Medical Pharmacology &amp; Physiol</option>
<option value="MED_ID">Medicine-Interdisciplinary</option>
<option value="MICROB">Microbiology</option>
<option value="MIL_SC">Military Science</option>
<option value="MISC">Miscellaneous</option>
<option value="MUS_APMS">Music-Applied Music</option>
<option value="MUSIC_NM">Music-Courses for Non-Majors</option>
<option value="MUS_ENS">Music-Ensemble Courses</option>
<option value="MUS_GENL">Music-General</option>
<option value="MUS_I_VR">Music-Instrumental And Vocal R</option>
<option value="MUS_I_VT">Music-Instrumental And Vocal T</option>
<option value="MUS_H_LI">Music-Music History And Litera</option>
<option value="MUS_THRY">Music-Music Theory</option>
<option value="NAT_R">Natural Resources</option>
<option value="NAVY">Naval Science</option>
<option value="NEUROL">Neurology</option>
<option value="NU_ENG">Nuclear Engineering</option>
<option value="NUCMED">Nuclear Medicine</option>
<option value="NURSE">Nursing</option>
<option value="NUTR_S">Nutritional Sciences</option>
<option value="OB_GYN">Obstetrics And Gynecology</option>
<option value="OC_THR">Occupational Therapy</option>
<option value="OPHTH">Ophthalmology</option>
<option value="P_R_TR">Parks, Recreation And Tourism</option>
<option value="PTH_AS">Pathology &amp; Anatomical Science</option>
<option value="PEA_ST">Peace Studies</option>
<option value="FINPLN">Personal Financial Planning</option>
<option value="PHIL">Philosophy</option>
<option value="PM_REH">Physical Medicine And Rehabili</option>
<option value="PH_THR">Physical Therapy</option>
<option value="PHYSCS">Physics</option>
<option value="PLNT_S">Plant Science</option>
<option value="POL_SC">Political Science</option>
<option value="PORT">Portuguese</option>
<option value="PSCHTY">Psychiatry</option>
<option value="PSYCH">Psychology</option>
<option value="PUB_AF">Public Affairs</option>
<option value="P_HLTH">Public Health</option>
<option value="RA_SCI">Radiologic Sciences</option>
<option value="RADIOL">Radiology</option>
<option value="REL_ST">Religious Studies</option>
<option value="RS_THR">Respiratory Therapy</option>
<option value="RM_LAN">Romance Languages</option>
<option value="RU_SOC">Rural Sociology</option>
<option value="RUSS">Russian</option>
<option value="SCI_AG_J">Science &amp; Agricultural Journ</option>
<option value="SOC_WK">Social Work</option>
<option value="SOCIOL">Sociology</option>
<option value="SOIL">Soil Science</option>
<option value="S_A_ST">South Asia Studies</option>
<option value="SPAN">Spanish</option>
<option value="SPC_ED">Special Education</option>
<option value="STAT">Statistics</option>
<option value="SSC">Student Success Center</option>
<option value="ST_ABRD">Study Abroad</option>
<option value="SURGRY">Surgery</option>
<option value="T_A_M">Textile And Apparel Management</option>
<option value="THEATR">Theatre</option>
<option value="V_BSCI">Veterinary Biomedical Science</option>
<option value="V_M_S">Veterinary Medicine &amp; Surgery</option>
<option value="VMED_I">Veterinary Medicine - Interdis</option>
<option value="V_PBIO">Veterinary Pathobiology</option>
<option value="WGST">Women's &amp; Gender Studies</option>
</select>